service: stripe-serverless

custom:
  secrets: ${file(secrets.json)}

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  profile: knope-compliments
  environment:
    SLACK_TOKEN: ${self:custom.secrets.slackToken} # Slack Token

functions:
  sendCompliment:
    handler: functions.sendCompliment
    events:
      - http:
          path: compliment
          method: post
          cors: true
